---
rke2_version: "v1.30.4+rke2r1"
rke2_vip: ""
rke2_server_url: ""
rke2_extra_sans: []
rke2_node_role: "control-plane"
rke2_node_taints: []
rke2_cluster_name: management
# Network interface kube-vip binds the VIP on (check with: ip link show)
rke2_vip_interface: eth0
